import { FoodBank, DemandSnapshot } from './types';

export const mockFoodBanks: FoodBank[] = [
  // ── Toronto ──────────────────────────────────────────────────────────
  {
    id: 'fb-to-01',
    name: 'Daily Bread Food Bank',
    city: 'toronto',
    latitude: 43.6089,
    longitude: -79.5023,
    weeklyCapacity: 1800,
    dailyCapacity: 260,
    phone: '416-203-0050',
    website: 'https://www.dailybread.ca',
    languages: ['en', 'fr'],
    dietaryTags: ['halal', 'vegetarian', 'gluten-free'],
  },
  {
    id: 'fb-to-02',
    name: 'Allan Gardens Food Bank',
    city: 'toronto',
    latitude: 43.6616,
    longitude: -79.3721,
    weeklyCapacity: 400,
    dailyCapacity: 60,
    phone: '416-604-5788',
    languages: ['en'],
    dietaryTags: [],
  },
  {
    id: 'fb-to-03',
    name: 'Fort York Food Bank',
    city: 'toronto',
    latitude: 43.6577,
    longitude: -79.4023,
    weeklyCapacity: 450,
    dailyCapacity: 65,
    phone: '416-203-3011',
    languages: ['en'],
    dietaryTags: [],
  },
  {
    id: 'fb-to-04',
    name: 'Mustard Seed',
    city: 'toronto',
    latitude: 43.6595,
    longitude: -79.3453,
    weeklyCapacity: 350,
    dailyCapacity: 50,
    phone: '416-465-6069',
    languages: ['en'],
    dietaryTags: [],
  },
  {
    id: 'fb-to-05',
    name: 'Scott Mission',
    city: 'toronto',
    latitude: 43.6595,
    longitude: -79.4029,
    weeklyCapacity: 1100,
    dailyCapacity: 160,
    website: 'https://scottmission.com',
    languages: ['en', 'fr'],
    dietaryTags: ['halal', 'gluten-free'],
  },
  {
    id: 'fb-to-06',
    name: 'Metropolitan United Church Outreach',
    city: 'toronto',
    latitude: 43.6524,
    longitude: -79.3766,
    weeklyCapacity: 300,
    dailyCapacity: 45,
    phone: '416-363-0331',
    languages: ['en'],
    dietaryTags: [],
  },
  {
    id: 'fb-to-07',
    name: 'North York Harvest Food Bank',
    city: 'toronto',
    latitude: 43.6889,
    longitude: -79.4805,
    weeklyCapacity: 1400,
    dailyCapacity: 200,
    phone: '416-635-7771',
    website: 'https://northyorkharvest.com',
    languages: ['en', 'ko', 'fa', 'ru'],
    dietaryTags: ['halal', 'kosher'],
  },
  {
    id: 'fb-to-08',
    name: 'Oriole Food Space',
    city: 'toronto',
    latitude: 43.7749,
    longitude: -79.3459,
    weeklyCapacity: 350,
    dailyCapacity: 50,
    phone: '647-772-3664',
    languages: ['en'],
    dietaryTags: [],
  },
  {
    id: 'fb-to-09',
    name: 'Roywood Food Bank',
    city: 'toronto',
    latitude: 43.7423,
    longitude: -79.3387,
    weeklyCapacity: 250,
    dailyCapacity: 35,
    phone: '437-886-4694',
    languages: ['en'],
    dietaryTags: [],
  },
  {
    id: 'fb-to-10',
    name: 'Jane Sheppard Food Bank',
    city: 'toronto',
    latitude: 43.7505,
    longitude: -79.5183,
    weeklyCapacity: 400,
    dailyCapacity: 60,
    phone: '416-746-0388',
    languages: ['en', 'so', 'ur'],
    dietaryTags: ['halal'],
  },
  {
    id: 'fb-to-11',
    name: 'The Stop Community Food Centre',
    city: 'toronto',
    latitude: 43.6725,
    longitude: -79.4514,
    weeklyCapacity: 900,
    dailyCapacity: 130,
    phone: '416-652-7867',
    website: 'https://www.thestop.org',
    languages: ['en', 'es', 'pt'],
    dietaryTags: ['vegetarian', 'vegan', 'culturally-specific'],
  },
  {
    id: 'fb-to-12',
    name: 'Parkdale Community Food Bank',
    city: 'toronto',
    latitude: 43.6412,
    longitude: -79.4362,
    weeklyCapacity: 500,
    dailyCapacity: 70,
    phone: '416-532-2375',
    languages: ['en', 'vi', 'zh'],
    dietaryTags: ['culturally-specific'],
  },
  {
    id: 'fb-to-13',
    name: 'Churches on the Hill Food Bank',
    city: 'toronto',
    latitude: 43.6879,
    longitude: -79.4021,
    weeklyCapacity: 300,
    dailyCapacity: 45,
    phone: '416-967-3842',
    languages: ['en'],
    dietaryTags: [],
  },
  {
    id: 'fb-to-14',
    name: 'Bloor West Food Bank',
    city: 'toronto',
    latitude: 43.6503,
    longitude: -79.4816,
    weeklyCapacity: 300,
    dailyCapacity: 45,
    languages: ['en'],
    dietaryTags: [],
  },
  {
    id: 'fb-to-15',
    name: 'Christie Ossington Neighbourhood Centre',
    city: 'toronto',
    latitude: 43.6626,
    longitude: -79.4197,
    weeklyCapacity: 400,
    dailyCapacity: 60,
    phone: '416-792-8941',
    languages: ['en', 'pt'],
    dietaryTags: [],
  },
  {
    id: 'fb-to-16',
    name: 'Feed Scarborough — Rouge Park Food Bank',
    city: 'toronto',
    latitude: 43.7654,
    longitude: -79.1837,
    weeklyCapacity: 500,
    dailyCapacity: 70,
    phone: '416-936-3975',
    languages: ['en', 'ta', 'bn'],
    dietaryTags: ['halal'],
  },
  {
    id: 'fb-to-17',
    name: 'Feed Scarborough — Clairlea Food Bank',
    city: 'toronto',
    latitude: 43.7145,
    longitude: -79.2843,
    weeklyCapacity: 400,
    dailyCapacity: 60,
    phone: '416-203-0050',
    languages: ['en', 'zh'],
    dietaryTags: [],
  },
  {
    id: 'fb-to-18',
    name: 'Feed Scarborough — Markham Road Food Bank',
    city: 'toronto',
    latitude: 43.7654,
    longitude: -79.1936,
    weeklyCapacity: 400,
    dailyCapacity: 60,
    languages: ['en'],
    dietaryTags: [],
  },
  {
    id: 'fb-to-19',
    name: 'Glen Everest Food Bank',
    city: 'toronto',
    latitude: 43.6935,
    longitude: -79.2632,
    weeklyCapacity: 300,
    dailyCapacity: 45,
    phone: '647-330-2254',
    languages: ['en'],
    dietaryTags: [],
  },
  {
    id: 'fb-to-20',
    name: 'McCowan Rd Food Bank',
    city: 'toronto',
    latitude: 43.7286,
    longitude: -79.2513,
    weeklyCapacity: 300,
    dailyCapacity: 45,
    phone: '647-330-2254',
    languages: ['en', 'ta'],
    dietaryTags: [],
  },
  {
    id: 'fb-to-21',
    name: 'Eastview Neighbourhood Community Centre',
    city: 'toronto',
    latitude: 43.6797,
    longitude: -79.3392,
    weeklyCapacity: 350,
    dailyCapacity: 50,
    phone: '416-392-1750',
    languages: ['en'],
    dietaryTags: [],
  },
  {
    id: 'fb-to-22',
    name: 'Bethany Baptist Church Food Bank',
    city: 'toronto',
    latitude: 43.6862,
    longitude: -79.3453,
    weeklyCapacity: 250,
    dailyCapacity: 35,
    phone: '647-366-9041',
    languages: ['en'],
    dietaryTags: [],
  },
  {
    id: 'fb-to-23',
    name: 'Nourish East End',
    city: 'toronto',
    latitude: 43.6746,
    longitude: -79.3212,
    weeklyCapacity: 300,
    dailyCapacity: 45,
    languages: ['en'],
    dietaryTags: [],
  },
  {
    id: 'fb-to-24',
    name: 'St Ann Parish Food Bank',
    city: 'toronto',
    latitude: 43.6616,
    longitude: -79.3436,
    weeklyCapacity: 300,
    dailyCapacity: 45,
    phone: '416-466-2127',
    languages: ['en'],
    dietaryTags: [],
  },

  // ── Mississauga ──────────────────────────────────────────────────────
  {
    id: 'fb-mi-01',
    name: 'The Mississauga Food Bank',
    city: 'mississauga',
    latitude: 43.6238,
    longitude: -79.6224,
    weeklyCapacity: 1600,
    dailyCapacity: 230,
    phone: '905-270-5589',
    website: 'https://www.themississaugafoodbank.org',
    languages: ['en', 'hi', 'pa', 'ur'],
    dietaryTags: ['halal', 'vegetarian'],
  },
  {
    id: 'fb-mi-02',
    name: 'The Compass',
    city: 'mississauga',
    latitude: 43.5567,
    longitude: -79.5766,
    weeklyCapacity: 500,
    dailyCapacity: 70,
    phone: '905-274-9309',
    languages: ['en'],
    dietaryTags: [],
  },
  {
    id: 'fb-mi-03',
    name: 'Eden Food for Change',
    city: 'mississauga',
    latitude: 43.5678,
    longitude: -79.7180,
    weeklyCapacity: 950,
    dailyCapacity: 140,
    phone: '905-785-3651',
    website: 'https://edenfoodforchange.org',
    languages: ['en', 'pa', 'ar'],
    dietaryTags: ['halal', 'gluten-free', 'culturally-specific'],
  },
  {
    id: 'fb-mi-04',
    name: 'ICNA Relief Canada — Mississauga',
    city: 'mississauga',
    latitude: 43.5904,
    longitude: -79.7476,
    weeklyCapacity: 600,
    dailyCapacity: 85,
    phone: '905-997-8777',
    languages: ['en', 'ur', 'ar'],
    dietaryTags: ['halal'],
  },
  {
    id: 'fb-mi-05',
    name: 'Malton Neighbourhood Services Food Bank',
    city: 'mississauga',
    latitude: 43.7099,
    longitude: -79.6414,
    weeklyCapacity: 600,
    dailyCapacity: 85,
    phone: '905-677-6270',
    languages: ['en', 'pa', 'ur', 'so'],
    dietaryTags: ['halal', 'culturally-specific'],
  },
  {
    id: 'fb-mi-06',
    name: 'Mavis Road Community Food Bank',
    city: 'mississauga',
    latitude: 43.5809,
    longitude: -79.6389,
    weeklyCapacity: 450,
    dailyCapacity: 65,
    phone: '905-281-9730',
    languages: ['en'],
    dietaryTags: [],
  },
  {
    id: 'fb-mi-07',
    name: 'Seva Food Bank',
    city: 'mississauga',
    latitude: 43.7024,
    longitude: -79.6355,
    weeklyCapacity: 700,
    dailyCapacity: 100,
    website: 'https://sevafoodbank.com',
    languages: ['en', 'pa', 'hi'],
    dietaryTags: ['vegetarian', 'culturally-specific'],
  },
  {
    id: 'fb-mi-08',
    name: 'Glen Erin Community Food Bank',
    city: 'mississauga',
    latitude: 43.5852,
    longitude: -79.7300,
    weeklyCapacity: 400,
    dailyCapacity: 60,
    phone: '905-821-1331',
    languages: ['en'],
    dietaryTags: [],
  },
  {
    id: 'fb-mi-09',
    name: 'Dundas Street East Food Bank',
    city: 'mississauga',
    latitude: 43.6016,
    longitude: -79.5837,
    weeklyCapacity: 450,
    dailyCapacity: 65,
    phone: '905-238-9008',
    languages: ['en'],
    dietaryTags: [],
  },

  // ── Waterloo Region ──────────────────────────────────────────────────
  {
    id: 'fb-wr-01',
    name: 'The Food Bank of Waterloo Region',
    city: 'waterloo',
    latitude: 43.4443,
    longitude: -80.4763,
    weeklyCapacity: 2000,
    dailyCapacity: 290,
    phone: '519-743-5576',
    website: 'https://www.thefoodbank.ca',
    languages: ['en', 'fr'],
    dietaryTags: ['halal', 'vegetarian', 'gluten-free'],
  },
  {
    id: 'fb-wr-02',
    name: 'Cambridge Self-Help Food Bank',
    city: 'waterloo',
    latitude: 43.3762,
    longitude: -80.3121,
    weeklyCapacity: 900,
    dailyCapacity: 130,
    phone: '519-622-6550',
    website: 'https://www.cambridgefoodbank.org',
    languages: ['en'],
    dietaryTags: ['halal', 'vegetarian'],
  },
  {
    id: 'fb-wr-03',
    name: 'House of Friendship — Emergency Food Hamper Program',
    city: 'waterloo',
    latitude: 43.4636,
    longitude: -80.4830,
    weeklyCapacity: 750,
    dailyCapacity: 110,
    phone: '519-742-0662',
    website: 'https://houseoffriendship.org',
    languages: ['en'],
    dietaryTags: ['culturally-specific', 'gluten-free'],
  },
];

// Demand snapshots keyed by foodBankId at seed-time; regenerated with jitter on seed.
export const mockDemandSnapshots: Omit<DemandSnapshot, 'foodBankId'>[] = [];
