import { NextRequest, NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';

export const maxDuration = 30;

const SYSTEM_PROMPT = `You are FoodRoute's intake AI. You quickly understand a household's food needs so we can route them to the right food bank.

Rules:
1. Ask ONE short question at a time. Max 1-2 sentences per response.
2. NO filler. No "I'm sorry to hear that", no "That sounds hard", no "I understand". Jump straight to the next question or action.
3. If someone says they have no food today or have young children with no food, treat this as critical — acknowledge briefly and move to routing immediately.
4. Gather: household size, any children, any dietary restrictions (halal/kosher/vegetarian/gluten-free/allergies), preferred language, how soon they need food.
5. You MUST complete intake within 2-3 user messages. After the user's 2nd reply you MUST classify on your next response. Do NOT ask more than 3 questions total.
6. Your FINAL message before classification must say exactly: "Got it. We're finding the best food bank for you now."

CRITICAL RULES:
- NEVER output JSON, code blocks, or structured data in your spoken text.
- When you have enough info (or after 2-3 exchanges — whichever comes first), you MUST add a line at the very end starting with "NEEDS_RESULT:" followed by JSON:
NEEDS_RESULT:{"urgency": "critical|high|moderate", "reasoning": "brief explanation", "done": true, "needs": {"languages": [], "dietaryNeeds": [], "culturalPreference": "", "freeText": "summary"}}
- The NEEDS_RESULT line is stripped before display — the person never sees it.
- If you are unsure, err toward "high". NEVER keep chatting to gather more info past 3 exchanges.

Urgency:
- critical: No food today/within 24 hours, or young children with no food
- high: Will run out of food within the week
- moderate: Planning ahead, has some food remaining

Be direct. Every word counts. CLASSIFY FAST.`;

interface Message {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { messages } = body as { messages: Message[] };

    if (!Array.isArray(messages)) {
      return NextResponse.json({ error: 'messages array is required' }, { status: 400 });
    }

    const apiKey = process.env.ANTHROPIC_API_KEY;
    if (!apiKey) {
      return NextResponse.json({ error: 'ANTHROPIC_API_KEY not configured' }, { status: 500 });
    }

    const anthropic = new Anthropic({ apiKey });
    const modelId = process.env.ANTHROPIC_MODEL ?? 'claude-sonnet-5';

    const userMessageCount = messages.filter(m => m.role === 'user').length;

    // Hard cutoff: if 5+ user messages, force classification from conversation history
    if (userMessageCount >= 5) {
      const conversationSummary = messages
        .filter(m => m.role === 'user')
        .map(m => m.content)
        .join('; ');
      return NextResponse.json({
        reply: "Got it. We're finding the best food bank for you now.",
        needs: {
          urgency: 'high' as const,
          reasoning: `Auto-classified after extended conversation: ${conversationSummary.slice(0, 200)}`,
          needs: { languages: [], dietaryNeeds: [], culturalPreference: '', freeText: conversationSummary.slice(0, 300) },
        },
      });
    }

    // Anthropic's Messages API takes only user/assistant turns and must start with 'user'.
    // The UI prepends a local-only greeting (role 'assistant') that was never generated by
    // the model — drop everything before the first real user message.
    const firstUserIdx = messages.findIndex((m) => m.role === 'user');
    const trimmedMessages = firstUserIdx === -1 ? [] : messages.slice(firstUserIdx);
    const conversationMessages = trimmedMessages
      .filter((m): m is Message & { role: 'user' | 'assistant' } => m.role === 'user' || m.role === 'assistant')
      .map((m) => ({ role: m.role, content: m.content }));

    let systemText = SYSTEM_PROMPT;

    // After 3 user messages, inject a hard nudge to force classification NOW
    if (userMessageCount >= 3) {
      systemText += '\n\nYou have enough information. You MUST classify NOW. Say "Got it. We\'re finding the best food bank for you now." and include the NEEDS_RESULT line. Do NOT ask any more questions.';
    }

    const result = await anthropic.messages.create({
      model: modelId,
      max_tokens: 600,
      system: systemText,
      messages: conversationMessages,
    });

    const textBlock = result.content.find((b) => b.type === 'text');
    const text = textBlock && 'text' in textBlock ? textBlock.text : '';

    // Extract needs JSON from the response — greedy match to handle nested braces
    let needs = null;

    // NEEDS_RESULT: format — grab everything from the opening { to the end of the string
    const needsMatch = /NEEDS_RESULT:\s*(\{[\s\S]*\})\s*$/.exec(text);
    if (needsMatch) {
      try {
        const parsed = JSON.parse(needsMatch[1].trim());
        if (parsed.done && parsed.urgency && parsed.reasoning) {
          needs = {
            urgency: parsed.urgency,
            reasoning: parsed.reasoning,
            needs: parsed.needs || null,
          };
        }
      } catch {
        // Not valid JSON, ignore
      }
    }

    // Legacy ```json format fallback
    if (!needs) {
      const jsonMatch = /```json\s*([\s\S]*?)```/.exec(text);
      if (jsonMatch) {
        try {
          const parsed = JSON.parse(jsonMatch[1].trim());
          if (parsed.done && parsed.urgency && parsed.reasoning) {
            needs = {
              urgency: parsed.urgency,
              reasoning: parsed.reasoning,
              needs: parsed.needs || null,
            };
          }
        } catch {
          // Not valid JSON, ignore
        }
      }
    }

    // Truncation-safe fallback: if the model started NEEDS_RESULT but the JSON never closed
    // (e.g. got cut off), still extract an urgency value with a regex so the user isn't stuck.
    if (!needs && /NEEDS_RESULT:/.test(text)) {
      const urgencyMatch = /"urgency"\s*:\s*"(critical|high|moderate)"/.exec(text);
      if (urgencyMatch) {
        const reasoningMatch = /"reasoning"\s*:\s*"([^"]*)"/.exec(text);
        needs = {
          urgency: urgencyMatch[1] as 'critical' | 'high' | 'moderate',
          reasoning: reasoningMatch?.[1] ?? 'Classified from conversation.',
          needs: { languages: [], dietaryNeeds: [], culturalPreference: '', freeText: '' },
        };
      }
    }

    // Clean the display text — strip all machine-readable data so only natural speech remains
    let displayText = text
      .replace(/NEEDS_RESULT:\s*\{[\s\S]*\}\s*$/g, '')       // NEEDS_RESULT line (well-formed, greedy)
      .replace(/NEEDS_RESULT:[\s\S]*$/g, '')                  // fallback: truncated/malformed NEEDS_RESULT (no closing brace)
      .replace(/```json[\s\S]*?```/g, '')                     // ```json blocks
      .replace(/\{[^}]*"urgency"\s*:[\s\S]*\}/g, '')          // any raw JSON with "urgency"
      .replace(/\{[^}]*"done"\s*:\s*true[\s\S]*\}/g, '')      // any raw JSON with "done": true
      .trim();

    return NextResponse.json({
      reply: displayText,
      needs,
    });
  } catch (err) {
    console.error('Converse API error:', err);
    return NextResponse.json(
      { error: 'Conversation failed. Please try again.' },
      { status: 500 }
    );
  }
}
